"""empty message

Revision ID: bc8264d6079b
Revises: bdaca53e8db1
Create Date: 2024-08-12 17:10:08.330892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text 

# revision identifiers, used by Alembic.
revision = 'bc8264d6079b'
down_revision = 'bdaca53e8db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ytube_text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_history', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ytube_text', schema=None) as batch_op:
        batch_op.drop_column('chat_history')

    # ### end Alembic commands ###
